#!/usr/bin/env bash
#Loops from 1 to 10 and:
#Display "bad luck" in the 4th time
#Display "good luck" in the 8th
#else Display "Best School"
i=0
while [$i -lt 10]
do
if [$i -eg 3]
then
echo "bad luck"
elif [$i -eg 7]
then
echo "good  luck"
else
echo "Best School"
fi
((i++))
done

