#!/usr/bin/env bash
#Display numbers from 1 to 20 and
#Display "bad luck from china " in the 4th time
#Display"bad luck from japan" in the 9th time
#Display "bad luck from italy" in the 17th time
i=1
while [$i -le 20]
do
echo "$i"
case $i in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17")echo "bad luck from Italy";;
case
((i++))
done

